---
title: "test_phylo_mcmcglmm"
output: html_document
date: "2023-09-01"
---

```{r}
library(nlme)
library(ape)
library(RColorBrewer)
library(ggplot2)
library(MCMCglmm)
library(tibble)
library(tidyverse)
library(r2glmm)
library(performance)

options(max.print=9999999)
```

# Real data

```{r}
bact_features = read.table("../../../data/genomics/bacteria/picard_collection.csv", sep=";", header=TRUE, na.strings = "")
phage_features = read.table("../../../data/genomics/phages/guelin_collection.csv", sep=";", header=TRUE)
interaction_matrix = read.table("../../../data/interactions/interaction_matrix.csv", sep=";", header=TRUE)
coli_receptors = read.table("../../../data/genomics/bacteria/outer_membrane_proteins/blast_results_cured_clusters=99_wide.tsv", sep="\t", header=TRUE)
coli_ds = read.table("../../../data/genomics/bacteria/defense_finder/370+host_defense_systems_subtypes.csv", sep=";", header=TRUE)

interactions_long = interaction_matrix %>% pivot_longer(cols = -c("bacteria"), names_to="phage", values_to="interaction")

bact_features$bacteria = make.names(bact_features$bacteria)
interactions_long$bacteria = make.names(interactions_long$bacteria)
interactions_long$interaction = as.integer(interactions_long$interaction > 0)
rownames(bact_features) = bact_features$bacteria
rownames(phage_features) = phage_features$phage
rownames(interaction_matrix) = interaction_matrix$bacteria

# Prepare categorical data
bact_features[is.na(bact_features[, "Klebs_capsule_type"]),"Klebs_capsule_type"] = "NA"
bact_features[is.na(bact_features[, "ABC_serotype"]), "ABC_serotype"] = "NA"
bact_features$Clermont_Phylo = as.factor(bact_features$Clermont_Phylo)
bact_features$ST_Warwick = as.factor(bact_features$ST_Warwick)
bact_features$O.type = as.factor(bact_features$O.type)
bact_features$H.type = as.factor(bact_features$H.type)
bact_features$LPS_type = as.factor(bact_features$LPS_type)
bact_features$Klebs_capsule_type = as.factor(bact_features$Klebs_capsule_type)
bact_features$ABC_serotype = as.factor(bact_features$ABC_serotype)

# Prepare receptors and DS

coli_receptors[is.na(coli_receptors),] = "NA"
coli_receptors = lapply(coli_receptors, as.factor)
coli_ds[,-1] = coli_ds[,-1] > 0 # to boolean
coli_ds$bacteria = make.names(coli_ds$bacteria)
n_obs_sys = colSums(coli_ds[,-1])

filter_out_non_frequent_sys = TRUE
if (filter_out_non_frequent_sys) {
  print(dim(coli_ds))
  print("Filtering out non frequent defense systems.")
  thresh_sys = 15
  print(paste("Threshold :", thresh_sys))
  coli_ds = data.frame(coli_ds$bacteria, coli_ds[,-1][, n_obs_sys > thresh_sys])
  colnames(coli_ds)[1] = "bacteria"
  print(dim(coli_ds))
}
bact_features = merge(bact_features, coli_receptors, by="bacteria")
bact_features = merge(bact_features, coli_ds, by="bacteria")
bact_features$bacteria = bact_features$bacteria
phage_features$phage = make.names(phage_features$phage)
rownames(bact_features) = bact_features$bacteria

bact_features = bact_features[,c("bacteria", "O.type", "H.type", "LPS_type", "Klebs_capsule_type", "ABC_serotype", "BTUB", "FADL", "FHUA", "LAMB", "LPTD", "NFRA", "OMPA", "OMPC", "OMPF", "TOLC", "TSX", "YNCD", colnames(coli_ds[,-1]))]

# Load phylogenetic trees
use_ultrametric_tree = TRUE
if (use_ultrametric_tree) {
  bact_phylo_tree = ape::read.tree("../../../data/genomics/bacteria/panacota/tree/370+host_ultrametric_tree_root=B992.nwk")
  bact_phylo_tree$tip.label = make.names(bact_phylo_tree$tip.label)
  # Root tree and scale to ultrametric tree
  bact_phylo_tree = ape::root(bact_phylo_tree, "B992", resolve.root=TRUE)
  # Get inverse of phylogenetic covariance matrix
  bact_Ainv = inverseA(bact_phylo_tree, scale=TRUE)$Ainv
} else {
  bact_phylo_tree = ape::read.tree("../../../data/genomics/bacteria/panacota/tree/370+host_tree_root=albertii.nwk")
  bact_phylo_tree = ape::root(bact_phylo_tree, "B992", resolve.root=TRUE)
  bact_phylo_tree$edge.length = abs(bact_phylo_tree$edge.length)
  bact_phylo_tree$edge.length = bact_phylo_tree$edge.length + 5e-9
  bact_Ainv = inverseA(bact_phylo_tree, scale=FALSE)$Ainv
}
phage_phylo_tree = ape::read.tree("../../../data/genomics/phages/tree/96_viridic_distance_phylogenetic_tree_algo=upgma.nwk")
bact_phylo_tree$edge.length = bact_phylo_tree$edge.length + 5e-9
phage_phylo_tree$edge.length = phage_phylo_tree$edge.length + 5e-9
phage_phylo_tree$tip.label = make.names(phage_phylo_tree$tip.label)
phage_Ainv = inverseA(phage_phylo_tree, scale=FALSE)$Ainv

# Check that all tree nodes are in the bact_features dataframe
i = 0
for (name in bact_phylo_tree$tip.label) {
  if (!(name %in% rownames(bact_features))) {
    # tibble::add_row(bact_features, bacteria=name)
    print(name)
    bact_phylo_tree = ape::drop.tip(bact_phylo_tree, name)
    i = i + 1
  }
}
print("Removed tips:")
print(i)

i = 0
for (name in unique(interactions_long$bacteria)) {
  if (!(name %in% bact_phylo_tree$tip.label)) {
    interactions_long = subset(interactions_long, bacteria != name)
    i = i + 1
  }
}
print("Removed bacteria:")
print(i)


avoid_low_cardinal_levels = TRUE
if (avoid_low_cardinal_levels) {
  print("Lumping low cardinality levels for O.type and H.type")
  thresh = 15
  
  bact_features = bact_features %>% mutate(H.type=if_else(H.type == "H-", "Other", H.type), ABC_serotype=if_else(ABC_serotype %in% c("1", "3", "6", "Unknown", "NA"), "Other", ABC_serotype), Klebs_capsule_type=if_else(Klebs_capsule_type %in% c("K10", "K127", "K16", "K39", "K54", "K25", "K63", "K9", "NA"), "Other", Klebs_capsule_type))
  bact_features$H.type = as.factor(bact_features$H.type)
  bact_features$ABC_serotype = as.factor(bact_features$ABC_serotype)
  
  bact_features = bact_features %>% mutate(O.type=fct_lump_min(O.type, thresh, other_level="Other"), H.type=fct_lump_min(H.type, thresh, other_level="Other"), BTUB=fct_lump_min(BTUB, thresh, other_level="Other"), FADL=fct_lump_min(FADL, thresh, other_level="Other"), FHUA=fct_lump_min(FHUA, thresh, other_level="Other"), LAMB=fct_lump_min(LAMB, thresh, other_level="Other"), LPTD=fct_lump_min(LPTD, thresh, other_level="Other"), NFRA=fct_lump_min(NFRA, thresh, other_level="Other"), OMPA=fct_lump_min(OMPA, thresh, other_level="Other"), OMPC=fct_lump_min(OMPC, thresh, other_level="Other"), OMPF=fct_lump_min(OMPF, thresh, other_level="Other"), TOLC=fct_lump_min(TOLC, thresh, other_level="Other"), TSX=fct_lump_min(TSX, thresh, other_level="Other"), YNCD=fct_lump_min(YNCD, thresh, other_level="Other")) #ABC_serotype=fct_lump_min(ABC_serotype, thresh, other_level="Other"))  # Avoid overparametrization by only taking into account O.type and H.type with more than n observations
  print("Min size threshold: ")
  print(thresh)
}
```

```{r}
scale_tree = FALSE
if (use_ultrametric_tree) {
  scale_tree = TRUE
}

phages = phage_features[5:length(phage_features$phage),"phage"]

for (phage_of_interest in phages) {
  print(phage_of_interest)
  
  save_path = paste(paste("summaries/AF+DS_niter=1000000", phage_of_interest, sep="/"), "MCMCglmm_niter=250000.res", sep="__")
  save_df = paste(paste("results/AF+DS_niter=1000000", phage_of_interest, sep="/"), "MCMCglmm_niter=250000.res", sep="__")
  save_model_path = paste(paste("models/AF+DS_niter=1000000", phage_of_interest, sep="/"), "MCMCglmm_niter=1000000.Rdata", sep="__")
  
  file.create(save_path)
  
  # Restrict to single phage
  interactions_long_phage = subset(interactions_long, phage == phage_of_interest)
  interactions_long_phage = merge(interactions_long_phage, bact_features, by="bacteria")

  # Get inverse of phylogenetic covariance matrix
  Ainv = inverseA(bact_phylo_tree, scale=FALSE)$Ainv
  
  # M0 = Full model
  prior.m0 <- list(G = list(G1 = list(V = 1, nu = 0.002)),  # Genetic (random effects)
                   R = list(R1 = list(V = 1, nu = 0.002)))  # Residual variance
  
  formula = as.formula(paste("interaction ~ ", paste(colnames(interactions_long_phage[,-(1:3)]), collapse=" + ")))
  
  m0 = MCMCglmm(formula, random = ~ bacteria, data = interactions_long_phage, ginverse = list(bacteria=Ainv), family="threshold", scale=scale_tree, nitt=1000000, thin=200, burnin=30000, prior=prior.m0, verbose=FALSE)
  
  # save model to Rdata object
  saveRDS(m0, file=save_model_path)
  
  # Write raw results
  sink(save_path)
  print(summary(m0))
  
  print("# Diagnostic")
  
  print("#### Heritability")
  herit <- m0[["VCV"]][,"bacteria"] / rowSums(m0$VCV)
  print(paste("mean(heritability) =", mean(herit)))
  print(paste("std(heritability) =", sqrt(var(herit))))
  
  print("### Autocorrelation diagnostic of covariates")
  autocorr.diag(m0[["Sol"]])
  
  print("### Effective size of covariates")
  effectiveSize(m0[["Sol"]])

  print("### Effective size of random effects (VCV)")
  effectiveSize(m0[["VCV"]])
  
  closeAllConnections()
  
  # save inference results into csv file
  sols = summary(m0)$solutions
  sols_df = data.frame(row.names(sols), sols, row.names = NULL)
  write.table(sols_df, save_df, sep="\t", quote=FALSE, row.names = FALSE)
} 
```

```{r "priors", warning=FALSE}
# M0 = Full model
prior.m0 <- list(G = list(G1 = list(V = 1, nu = 0.002)),  # Genetic (random effects)
                 R = list(R1 = list(V = 1, nu = 0.002)))  # Residual variance

# M1 = Full model
prior.m1 <- list(G = list(G1 = list(V = 1, nu = 0.002)),  # Genetic (random effect)
                 R = list(R1 = list(V = 1, nu = 0.002)))  # Residual variance

# M2 = Full model
prior.m2 <- list(G = list(G1 = list(V = 1, nu = 0.002)),  # Genetic (random effect)
                 R = list(R1 = list(V = 1, nu = 0.002)))  # Residual variance
```


```{r}
m.intercept = MCMCglmm(interaction ~ 1, random = ~ animal, data = interactions_long, ginverse = list(animal=Ainv), family="threshold", scale=FALSE, nitt=150000, thin=50, burnin=30000, prior=prior.m0, verbose=FALSE)

m0 = MCMCglmm(interaction ~ Clermont_Phylo + O.type + H.type + LPS_type + Klebs_capsule_type, random = ~ animal, data = interactions_long, ginverse = list(animal=Ainv), family="threshold", scale=FALSE, nitt=150000, thin=50, burnin=30000, prior=prior.m0, verbose=FALSE)

m1 = MCMCglmm(interaction ~ Clermont_Phylo + O.type + H.type + LPS_type, random = ~ animal, data = interactions_long, ginverse = list(animal=Ainv), family="threshold", scale=FALSE, nitt=55000, thin=20, burnin=5000, prior=prior.m1, verbose=FALSE)

m2 = MCMCglmm(interaction ~ Clermont_Phylo + H.type + LPS_type + Klebs_capsule_type, random = ~ animal, data = interactions_long, ginverse = list(animal=Ainv), family="threshold", scale=FALSE, nitt=55000, thin=20, burnin=5000, prior=prior.m1, verbose=FALSE)
```

```{r}
summary(m.intercept)
```


```{r}
summary(m0)
```

```{r}
summary(m1)
```

```{r}
summary(m2)
```

### Compute *heritability*


```{r}
herit <- m.intercept[["VCV"]][ , "animal"] / rowSums(m.intercept$VCV)

mean(herit)
```


### *Diagnostic*

##### Check for *autocorrelation*

```{r}
print("### Effective size of covariates")
effectiveSize(m0[["Sol"]])
```

```{r}
print("### Effective size of random effects (VCV)")
effectiveSize(m0[["VCV"]])
```

```{r}
print("Autocorrelation diagnostic of covariates")
autocorr.diag(m0[["Sol"]])
```
